---

- name: main cfg template
  template:
    src: "syslog-ng_{{ansible_os_family}}-{{ansible_distribution_major_version}}.conf.j2"
    dest: "/etc/syslog-ng/syslog-ng.conf"
    owner: root
    group: root
    mode: 0644
  when: sng_cfg_template is defined
  notify: svc restart syslog-ng

- name: conf.d templates
  template:
    src: "syslog-ng-confd.j2"
    dest: "{{sng_conf_dir}}/{{item.dest}}"
    owner: "{{sng_owner | default('root')}}"
    group: "{{sng_group | default('root')}}"
    mode: "{{sng_mode | default('0644')}}"
  with_items: "{{sng_templates}}"
  notify: svc restart syslog-ng

- name: copy conf.d files
  copy:
    src={{item.src}}
    dest={{item.dest}}
    owner={{sng_owner | default('root')}}
    group={{sng_group | default('root')}}
    mode={{sng_mode | default('0644')}}
  with_items: "{{sng_copy_files}}"
  notify: svc restart syslog-ng

- name: certificate content
  copy:
    content: "{{item.content}}"
    dest: "/etc/pki/tls/{{item.type}}/{{item.filename}}"
    owner: "{{item.owner|default(sng_owner)}}"
    group: "{{item.group|default(sng_group)}}"
    mode: "{{item.mode|default(sng_cert_mode)}}"
  with_items: "{{sng_certs}}"
  when: item.type is defined and item.filename is defined and item.content is defined and item.src is not defined
  notify: svc restart syslog-ng

- name: certificate file
  copy:
    src: "{{item.file}}"
    dest: "/etc/pki/tls/{{item.type}}/{{item.filename}}"
    owner: "{{item.owner|default(sng_owner)}}"
    group: "{{item.group|default(sng_group)}}"
    mode: "{{item.mode|default(sng_cert_mode)}}"
  with_items: "{{sng_certs}}"
  when: item.type is defined and item.filename is defined and item.file is defined and item.content is not defined
  notify: svc restart syslog-ng

- name: hashicorp vault /pki/issue
  set_fact: sng_hvault_certs="{{ lookup('hashvault', 'method=write vaultkey=pki/issue/'+ sng_hvault_pki_role +' common_name=' + ansible_nodename) }}"
  when: sng_hvault and sng_hvault_pki_role

- name: hashicorp vault ca cert
  copy:
    content: "{{sng_hvault_certs.issuing_ca}}"
    dest: "/etc/pki/tls/certs/syslog-ng_ca.crt"
    owner: "{{sng_owner}}"
    group: "{{sng_group}}"
    mode: 0640
  when: sng_hvault and sng_hvault_certs.issuing_ca is defined
  notify: svc restart syslog-ng

- name: hashicorp vault server cert
  copy:
    content: "{{sng_hvault_certs.certificate}}"
    dest: "/etc/pki/tls/certs/syslog-ng.crt"
    owner: "{{sng_owner}}"
    group: "{{sng_group}}"
    mode: 0640
  when: sng_hvault and sng_hvault_certs.certificate is defined
  notify: svc restart syslog-ng

- name: hashicorp vault private key
  copy:
    content: "{{sng_hvault_certs.private_key}}"
    dest: "/etc/pki/tls/private/syslog-ng.key"
    owner: "{{sng_owner}}"
    group: "{{sng_group}}"
    mode: 0640
  when: sng_hvault and sng_hvault_certs.private_key is defined
  notify: svc restart syslog-ng

- name: get ca hash
  command: openssl x509 -noout -hash -in /etc/pki/tls/certs/syslog-ng_ca.crt
  register: ca_hash

- name: create ssl directory
  file: path=/etc/syslog-ng/ssl state=directory mode=0755

- name: symlink ca hash to ca cert
  file:
    src: /etc/pki/tls/certs/syslog-ng_ca.crt
    dest: "/etc/syslog-ng/ssl/{{ca_hash.stdout}}.0"
    state: link
  when: ca_hash.stdout is defined

- name: service enable, start
  service:
    name: "{{sng_svc_name}}"
    state: "{{sng_svc_state}}"
    enabled: "{{sng_svc_enabled}}"

