---

#- name: add repo
#  template:
#    src: elasticsearch.repo.j2
#    dest: /etc/yum.repos.d/elasticsearch.repo
#    mode: 0644

- name: install deps
  yum:
    name: http://mirror.sfo12.us.leaseweb.net/epel/6/x86_64/hiredis-0.10.1-3.el6.x86_64.rpm
    state: installed

- name: install pkg
  yum:
    name: "{{item}}"
    state: installed
  with_items:
    - syslog-ng
    - syslog-ng-redis
    - syslog-ng-json

- name: main config
  template:
    src: "{{ item }}.j2"
    dest: "/etc/syslog-ng/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - syslog-ng.conf
  notify: svc restart syslog-ng

- name: config conf.d
  template:
    src: "{{ item }}.j2"
    dest: "/etc/syslog-ng/conf.d/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - 01-internal.conf
    - 10-remote514-to-redis.conf
  notify: svc restart syslog-ng

- name: service enable, start
  service: name=syslog-ng state={{sng_svc_state}} enabled={{sng_svc_enabled}}

