---

#- name: add repo
#  template:
#    src: elasticsearch.repo.j2
#    dest: /etc/yum.repos.d/elasticsearch.repo
#    mode: 0644

- name: install deps
  yum:
    name: http://mirror.sfo12.us.leaseweb.net/epel/6/x86_64/hiredis-0.10.1-3.el6.x86_64.rpm
    state: installed

- name: install pkg
  yum:
    name: "{{item}}"
    state: installed
  with_items:
    - syslog-ng
    - syslog-ng-redis
