---

- include: setup-RedHat.yml
  when: ansible_distribution == "RedHat" or ansible_distribution == "CentOS"

- name: main config
  template:
    src: "{{ item }}.j2"
    dest: "/etc/syslog-ng/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - syslog-ng_{{ansible_distribution}}-{{ansible_distribution_major_version}}.conf
  notify: svc restart syslog-ng

- name: config conf.d
  template:
    src: "{{ item }}.j2"
    dest: "/etc/syslog-ng/conf.d/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - 01-internal.conf
    - 10-remote514-to-redis.conf
  notify: svc restart syslog-ng

- name: service enable, start
  service: name=syslog-ng state={{sng_svc_state}} enabled={{sng_svc_enabled}}

